spring:
  h2.console:
     enabled: true
     path: '/console'
  main:
    banner-mode: off
  datasource:
   url: 'jdbc:h2:file:./todoDB'
  jpa.hibernate.ddl-auto: update
task:
 template:
   allowMultipleTasks: false



